name: Build & Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          sleep 5
          if [[ "${{ github.event.head_commit.message }}" == *"installfail"* ]]; then
            echo "Dependency installation failed!"
            exit 1
          fi
          echo "Dependencies installed successfully!"

      - name: Build project
        run: |
          echo "Building project..."
          sleep 10
          if [[ "${{ github.event.head_commit.message }}" == *"buildfail"* ]]; then
            echo "Build failed due to syntax error!"
            exit 1
          fi
          echo "Build completed successfully!"

      - name: Run tests
        run: |
          echo "Running tests..."
          sleep 5
          if [[ "${{ github.event.head_commit.message }}" == *"testfail"* ]]; then
            echo "Unit tests failed!"
            exit 1
          fi
          echo "All tests passed!"
